inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**'

Style:
  AlignParameters:
    EnforcedStyle: with_fixed_indentation

  IndentationConsistency:
    EnforceStyle: rails

  IndentHash:
    EnforcedStyle: consistent 

Lint/BlockAlignment:
  AlignWith: start_of_block
