AllCops:
  Exclude:
    - 'bin/**'

inherit_from: .rubocop_todo.yml

Style:
  AlignParameters:
    EnforcedStyle: with_fixed_indentation

  IndentationConsistency:
    EnforceStyle: rails

  IndentHash:
    EnforcedStyle: consistent 
