web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PG_USERNAME: postgres
    PG_HOST: db
  command: bundle exec unicorn -l 0.0.0.0:3000

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign
