web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PG_USERNAME: postgres
    PG_HOST: db

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign

redis:
  image: redis
  ports:
    - "6379:6379"
