web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - rabbitmq
  environment:
    PG_USERNAME: postgres
    PG_HOST: db

  env_file:
    - '.env.web'
  command: bundle exec rails s -b 0.0.0.0

db:
  image: postgres
  ports:
    - "5432"

rabbitmq:
  image: rabbitmq
  ports:
    - "5672"
    - "15672"
    - "8080"
