# Production Settings for Champaign

# General Champaign settings.
     secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
     omniauth_client_secret: <%= ENV['OMNIAUTH_CLIENT_SECRET'] %>
     omniauth_client_id: <%= ENV['OMNIAUTH_CLIENT_ID'] %>
     liquid_templating_source: <%= ENV['LIQUID_TEMPLATING_SOURCE'] || 'file' %>


# AWS Config Variables.
     aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
     aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
     aws_region: <%= ENV['AWS_REGION'] %>
     sqs_queue_url: <%= ENV['SQS_QUEUE_URL'] %>


# Direct ActionKit Connection variables.
     ak_processor_url: <%= ENV['AK_PROCESSOR_URL'] %>
     ak_username: <%= ENV['AK_USERNAME'] %>
     ak_password: <%= ENV['AK_PASSWORD'] %>


# CloudFront config Variables.
     cloudfront_url: <%= ENV['CLOUDFRONT_URL'] %>
     fog_directory: <%= ENV['FOG_DIRECTORY'] %>
     rails_serve_static_files: <%= ENV['RAILS_SERVE_STATIC_FILES'] %>
     compile_static: <%= ENV['COMPILE_STATIC'] %>


# NewRelic Connection information.
     newrelick_license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>


# Social media connection information.
     facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
     share_progress_api_key: <%= ENV['SHARE_PROGRESS_API_KEY'] %>
