web:
  image: soutech/champaign_web:$CIRCLE_SHA1
  links:
    - db
  command: /myapp/circle/specs-and-rake-tasks
  volumes:
    - .:/myapp
  env_file:
    - test.env

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign
